# Jykell configuration
markdown: redcarpet
highlighter: pygments
paginate: 5
language: 'en-uk'

# Website info
name: 'Curosity is the most powerful thing you own'
description: "A beautiful narrative written an elegant publishing platform. The story begins here."

# Author's info
author: 'Deepak Kumar Gupta'
# edit 'categories' in the front matter of every post to match this username
nickname: casper
bio: 'A full time technologist cum foodie. He spends most of the time playing with open source tools and prefers hanging out with friends. Deepak has been a taveller since ages, besides being a hardcore biker and loves doing photogrpahy as hobby.'
location: 'Bangalore, INDIA'
url: 'http://hellodk.github.io/'
image: 'assets/images/casper.png'

short_url: 'hellodk.github.io/'
#google_analytics: UA-69281367-1
disqus: username
# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: /

# Permalinks
permalink: /:title
# permalink: /author/:username
# permalink: /tag/:tag


# gems and other configs
gems: [jekyll-paginate]
exclude: [vendor]

# Additional settings available on the front-matter
# Site logo in the index.html (as in demo.ghost.io)
# Author's page cover in _layouts/author.html
# The same for page.html and tag.html layouts
# Post's page cover as a per-post basis _posts/...
# Disqus comments as a per-post basis
# ...


# Settings for builing master branch with travis-ci
# with jekyll-travis

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
safe: false
lsi: false
username: hellodk
repo: hellodk.github.io
branch: master
relative_source: ../jasper/
destination: ../jasper-pages/
production_url:  https://hellodk.github.io/
source_url:      https://github.com/hellodk/

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
