source "https://rubygems.org"

gem "jekyll"
#gem "jekyll", "~> 3.9.0"
gem "rdiscount"
gem "pygments.rb"
gem "github-pages"
# gem "github-pages", "~> 213"
gem "rake", "~> 12.3.3"
gem 'execjs'
gem 'libv8'
gem 'RedCloth'
gem 'redcarpet'
gem "rss"
gem 'liquid', '>= 5.4.0'

# gem "rdiscount"
# gem "pygments.rb"
# gem "github-pages"
# gem "rake"
# gem 'execjs'
# gem 'redcarpet'


#gem 'therubyracer', :platforms => :ruby
